atlasv2_h1:
  name: "atlasv2_h1"
  year_month: "2022-07"
  # Benign period: 2022-07-15..2022-07-18
  # Single attack engagement: 2022-07-19 with spillover into 2022-07-20 UTC.
  # Keep the entire engagement in test to avoid splitting the same attack across
  # validation and test.
  train_days: [ 15, 16, 17, 18 ]
  val_days: [ ]
  test_days: [ 19, 20 ]
  timezone: "UTC"

atlasv2_h2:
  name: "atlasv2_h2"
  year_month: "2022-07"
  # Benign period: 2022-07-15..2022-07-18
  # Single attack engagement: 2022-07-19 with spillover into 2022-07-20 UTC.
  # Keep the entire engagement in test to avoid splitting the same attack across
  # validation and test.
  train_days: [ 15, 16, 17, 18 ]
  val_days: [ ]
  test_days: [ 19, 20 ]
  timezone: "UTC"
