name: MAGIC
channels:
- conda-forge
- defaults
dependencies:
- python=3.9.23
- pip
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu116
  - numpy<2
  - torch==1.12.1+cu116
  - torchvision==0.13.1+cu116
  - torchaudio==0.12.1
  - dgl==1.0.0
  - scikit-learn==1.2.2
  - polars==1.36.1
  - xxhash
  - wandb
